version: '2'

services:
    fpm:
        build: .
        volumes_from: [data]
        environment:
            - ROOT
        environment:
            - VIRTUAL_PORT=9000
            - SYMFONY_ENV=dev

    nginx:
        image: nginx:1.13.8
        volumes_from: [fpm]
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        environment:
            VIRTUAL_HOST: foxnot.docker
            VIRTUAL_PORT: 80
        ports:
            - 80:80

    mysql:
        image: mysql:5.7
        entrypoint: /opt/bin/override/entrypoint.sh
        volumes:
            - ./docker/mysql:/opt/bin/override/
        command: mysqld
        environment:
            MYSQL_ROOT_PASSWORD: foxnot
            MYSQL_DATABASE: foxnot
            MYSQL_USER: foxnot
            MYSQL_PASSWORD: foxnot
            VIRTUAL_HOST: mysql.foxnot.docker
            VIRTUAL_PORT: 3306
        ports:
            - 3306:3306

    redis:
        image: redis:3-alpine

    mailcatcher:
        image: jeanberu/mailcatcher:0.6.5

    graphiql:
        image: langa/graphiql.io
        ports:
            - 3000:3000

    data:
        image: alpine
        command: echo 0
        volumes:
            - .:/var/www/html
            - ~/.yarn:/var/www/.yarn
            - ~/.npm:/var/www/.npm
            - ~/.yarn-config:/var/www/.yarn-config
            - ~/.yarn-cache:/var/www/.yarn-cache
            - ~/.cache:/var/www/.cache
            - ~/.config:/var/www/.config
            - ~/.composer:/var/www/.composer
            - ~/.yarnrc:/var/www/.yarnrc
