#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app:
#    resource: "../src/Controller/"
#    type:     annotation

overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
    prefix: /graphql

