<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\GraphQL\Relay\Node\GlobalIdFieldResolver' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Definition/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Definition/Resolver/AliasedInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/GraphQL/Relay/Node/GlobalIdFieldResolver.php';

return $this->services['Overblog\GraphQLBundle\GraphQL\Relay\Node\GlobalIdFieldResolver'] = new \Overblog\GraphQLBundle\GraphQL\Relay\Node\GlobalIdFieldResolver();
