<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.event_listener.request_file_listener' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/EventListener/RequestFilesListener.php';

return $this->services['overblog_graphql.event_listener.request_file_listener'] = new \Overblog\GraphQLBundle\EventListener\RequestFilesListener(($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
