<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.definition.boolean_type' shared service.

include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Type/Definition/Type.php';

return $this->services['overblog_graphql.definition.boolean_type'] = \GraphQL\Type\Definition\Type::boolean();
