<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.command.compile' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Command/CompileCommand.php';

return $this->services['overblog_graphql.command.compile'] = new \Overblog\GraphQLBundle\Command\CompileCommand(($this->services['overblog_graphql.cache_compiler'] ?? $this->getOverblogGraphql_CacheCompilerService()));
