<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.controller.graphql' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Request/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Request/BatchParser.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Controller/GraphController.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Request/Parser.php';

return $this->services['overblog_graphql.controller.graphql'] = new \Overblog\GraphQLBundle\Controller\GraphController(new \Overblog\GraphQLBundle\Request\BatchParser(), ($this->services['overblog_graphql.request_executor'] ?? $this->load(__DIR__.'/getOverblogGraphql_RequestExecutorService.php')), ($this->services['overblog_graphql.request_parser'] ?? $this->services['overblog_graphql.request_parser'] = new \Overblog\GraphQLBundle\Request\Parser()), false, 'relay');
