<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.command.debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Command/DebugCommand.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Resolver/AbstractResolver.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Resolver/AbstractProxyResolver.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Resolver/MutationResolver.php';

return $this->services['overblog_graphql.command.debug'] = new \Overblog\GraphQLBundle\Command\DebugCommand(($this->services['overblog_graphql.type_resolver'] ?? $this->load(__DIR__.'/getOverblogGraphql_TypeResolverService.php')), ($this->services['overblog_graphql.mutation_resolver'] ?? $this->services['overblog_graphql.mutation_resolver'] = new \Overblog\GraphQLBundle\Resolver\MutationResolver()), ($this->services['overblog_graphql.resolver_resolver'] ?? $this->load(__DIR__.'/getOverblogGraphql_ResolverResolverService.php')));
