<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.command.dump_schema' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Command/GraphQLDumpSchemaCommand.php';

return $this->services['overblog_graphql.command.dump_schema'] = new \Overblog\GraphQLBundle\Command\GraphQLDumpSchemaCommand($this, 'classic', ($this->targetDirs[3].'/src'));
