<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphiql.controller' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphiql-bundle/Config/GraphiQLViewJavaScriptLibraries.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphiql-bundle/Config/GraphiQLViewConfig.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphiql-bundle/Config/GraphiQLControllerEndpoint.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphiql-bundle/Config/GraphQLEndpoint/RouteResolver.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphiql-bundle/Controller/GraphiQLController.php';

return $this->services['overblog_graphiql.controller'] = new \Overblog\GraphiQLBundle\Controller\GraphiQLController(($this->services['twig'] ?? $this->getTwigService()), new \Overblog\GraphiQLBundle\Config\GraphiQLViewConfig(new \Overblog\GraphiQLBundle\Config\GraphiQLViewJavaScriptLibraries('0.11', '15.6', '2.0'), '@OverblogGraphiQL/GraphiQL/index.html.twig'), new \Overblog\GraphiQLBundle\Config\GraphQLEndpoint\RouteResolver(($this->services['router'] ?? $this->getRouterService()), array(0 => 'Overblog\\GraphiQLBundle\\Config\\GraphQLEndpoint\\Helpers\\OverblogGraphQLBundleEndpointResolver', 1 => 'getByName')));
