<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\GraphQL\Relay\Node\PluralIdentifyingRootFieldResolver' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Definition/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/Definition/Resolver/AliasedInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/GraphQL/Relay/Node/PluralIdentifyingRootFieldResolver.php';
include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Executor/Promise/PromiseAdapter.php';
include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php';

return $this->services['Overblog\GraphQLBundle\GraphQL\Relay\Node\PluralIdentifyingRootFieldResolver'] = new \Overblog\GraphQLBundle\GraphQL\Relay\Node\PluralIdentifyingRootFieldResolver(($this->privates['overblog_graphql.promise_adapter.default'] ?? $this->privates['overblog_graphql.promise_adapter.default'] = new \GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter()));
