<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\__DEFINITIONS__\ProductType' shared service.

return $this->services['Overblog\GraphQLBundle\__DEFINITIONS__\ProductType'] = new \Overblog\GraphQLBundle\__DEFINITIONS__\ProductType($this);
