<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBYFSxLP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBYFSxLP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBYFSxLP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBYFSxLP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBYFSxLP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BYFSxLP',
    'container.build_id' => 'e0dacda7',
    'container.build_time' => 1516959054,
));
